name: ci

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  format-lint-typecheck-test:
    name: Format, lint, typecheck, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          set -xe
          npm ci
          npm run format
          npm run lint 
          npm run typecheck
          npm run test:ci

  publish:
    name: Publish to npm
    needs: format-lint-typecheck-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          set -xe
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
