name: release

on:
  release:
    types: [published]

jobs:
  lint-format-typecheck-test-build:
    name: Lint, format, typecheck, test, and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          set -xe
          npm ci
          npm run lint 
          npm run format
          npm run typecheck
          npm run test:ci
          npm run build

  publish:
    name: Publish to npm
    needs: lint-format-typecheck-test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          set -xe
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
